module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'console',
        'gateway',
        'shared',
        'sdk',
        'ai',
        'contracts',
        'ai-core',
        'compliance',
        'settlement',
        'liquidity',
        'infra',
        'deps',
      ],
    ],
  },
};
