[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
fuzz = true
fuzz_runs = 1000
invariant = true
invariant_runs = 1000

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = []

# Coverage
coverage = true
coverage_paths = ["contracts"]

# Verbose output
verbosity = 2

# RPC endpoints
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://localhost:8545"

# Etherscan API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Fork configuration
[fork]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# Solidity compiler settings
[profile.default.fuzz]
dictionary_weight = 40
include_storage = true
include_push_byte = true

[profile.default.invariant]
fail_on_revert = false
depth = 15
fail_on_revert = false

# Development profile
[profile.dev]
optimizer = false
optimizer_runs = 0
via_ir = false
verbosity = 3

# Production profile
[profile.prod]
optimizer = true
optimizer_runs = 1000000
via_ir = true
verbosity = 1
gas_reports = ["*"]

# Testing profile
[profile.test]
optimizer = false
optimizer_runs = 0
via_ir = false
verbosity = 4
fuzz = true
fuzz_runs = 10000
invariant = true
invariant_runs = 10000
